name: Cypress Tests

on:
  workflow_dispatch:

env:
  CYPRESS: ${{ secrets.CYPRESS }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: log1
        run: echo $CYPRESS - ${{ secrets.CYPRESS }}

      - name: log2
        run: echo $CYPRESS_RECORD_KEY - ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Set Envs
        run: echo $CYPRESS > ./cypress.env.json

      - name: Cypress run        
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true 
        env:
          CYPRESS_RECORD_KEY: $CYPRESS_RECORD_KEY
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
