name: Cypress Tests

on:
  push:
    branches:
      - master

env:
  CYPRESS: ${{ secrets.CYPRESS }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  print-cla-1:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set Envs
        run: echo "CLA TE AMO"

  print-cla-2:
    needs: print-cla-1
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set Envs
        run: echo "CLA TE AMO mas nem tanto"
      
  cypress-run:
    needs: print-cla-2
    runs-on: ubuntu-latest
    environment: production

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Envs
        run: echo $CYPRESS > ./cypress.env.json

      - name: Cypress run        
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true 
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
